### ISSUE TITLE
[Turing] 실패율 -> 정말 실패

### ISSUE THREAD

**Issue by AirPodsNote** [OpenBible3438/SwiftMaster17_Team13_Study#65]
func solution(_ N:Int, _ stages:[Int]) -> [Int] {
    
    // 총 플레이어 수를 카운트
    var players = stages.count
    
    // 스테이지별 실패율 저장할 배열
    // 딕셔너리 vs 어레이..
    var failureRates = Array(repeating: (index: 0, rate: 0.0), count: N)
    
    // 스테지의 계산 스타트
    for i in 1...N {
        // 현재 스테이지
        let current = stages.filter { $0 == i }.count
        
    
        // 실패율 계산 부분
        // 도달 X -> 0.0 처리
        let failureRate = players > 0 ? Double(current) / Double(players) : 0.0
        
        // 실패율 i-1번에 저장
        failureRates[i-1] = (i, failureRate)
        
        // 다음스테이지 플레이어 마이너스
        players -= current
    }

    // 정렬 -> 여기서 아마 시간초과 5, 22 번
    return failureRates.sorted { $0.rate > $1.rate || ($0.rate == $1.rate && $0.index < $1.index) }.map { $0.index }
}

**Comment by AKAPUCH** [comment]
@AirPodsNote 
for문을 반복할 때마다 클리어하지 못한 사람 수를 계산해주고 있어 시간초과가 발생하는 것 같아요!
stages의 최대길이는 200000, N의 최대값은 500으로 filter 메서드는 전체 배열을 다 검사하기 때문에 대략 1억번의 연산을 하게 될 꺼에요

```swift
 let current = stages.filter { $0 == i }.count
```

어떻게 하면 매번 세지 않고 사람 수를 계산해 줄 수 있을까요? 
여러 방법이 있겠지만 스테이지의 계산을 시작하시기 전에 for문으로 한번 반복하여(최악의 경우 20만번) 스테이지별 사람 수를 저장해 놓는 것을 추천드려요.

**Comment by AirPodsNote** [comment]
오.. 땡큐.. 파카님 바로 시행해봅니다
주말 잘 보내세용~~
